[package]
name = "workflow-worker"
version = "0.1.0"
edition = "2021"

[dependencies]
cli-common = { path = "../cli-common" }
workflow-core = { path = "../workflow-core" }
log = "0.4"
anyhow = "1.0"
serde_derive = "1.0"
serde = "1.0"
actix-web = "4"
